### PR TITLE
minimal setup

### PR DESCRIPTION
**Pull request by musketyr**
run `./gradlew :local-server:runShadow` to run local server 
run `./gradlew :lambda-shipment:deployLambda` to deploy lambda to AWS (after proper setup)

### CODE REVIEW

**Comment by musketyr** [comment]
also remember, that the endpoint is available under `http://localhost:8888/shipment/shipment` (first `shipment` comes from the name of the controller)

**Comment by drissamri** [comment]
wow, thanks for taking the time! I'll have a look today!

**Comment by musketyr** [comment]
oh, I had to forgot to add it to Git 🤔 

it's the same as the one from the https://github.com/agorapulse/micronaut-libraries docs

```
configurations {
    lambda.extendsFrom runtime
    testCompile.extendsFrom lambda
}

dependencies {
    lambda "com.agorapulse:micronaut-function-aws-agp:$micronautLibrariesVersion"

    compile "io.micronaut:http-server"
    compile "io.micronaut:router"

    // gru for aws lambda can help you testing lambda fuctions
    // https://agorapulse.github.io/gru/
    testCompile "com.agorapulse:gru-api-gateway:0.6.3"
}

task buildZip(type: Zip) {
    from compileGroovy
    from processResources
    into('lib') {
        from configurations.lambda
    }
}

build.dependsOn buildZip
```

it's stll needed as it declares  `buildZip` task which you will still need with Terraform to create the deployment package

**Comment by musketyr** [comment]
also there is no need to have an `application` plugin in the lambda project, you run it locally using the `local-server` project

**Pull request merged**
